# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('event_date', models.DateField(verbose_name='event date')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('post_date', models.DateField(blank=True, null=True, verbose_name='date posted')),
                ('event_desc', models.TextField()),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
