# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170826_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
    ]
