# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170913_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name='date of event'),
        ),
    ]
