# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('other_name', models.CharField(blank=True, max_length=30, null=True)),
                ('matric_no', models.CharField(error_messages={'unique': 'A user with that matric number already exists.'}, max_length=12, unique=True, verbose_name='Matric Number')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1, verbose_name='sex')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('level', models.IntegerField(choices=[(1, 100), (2, 200), (3, 300), (4, 400), (5, 500), (6, 600)])),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Date Registered')),
                ('alumni', models.BooleanField(default=False)),
            ],
        ),
    ]
