# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2006-07-06 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dept',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Department'),
            preserve_default=False,
        ),
    ]
