# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20060707_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(choices=[(1, 100), (2, 200), (3, 300), (4, 400), (5, 500), (6, 'alumni')]),
        ),
    ]
