# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20170818_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='matric_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.AddField(
            model_name='member',
            name='committee',
            field=models.CharField(choices=[('cty', 'Catch Them Young'), ('com', 'Petro Bowl / Quiz'), ('reg', 'Registration')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='fullname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='dept',
            field=models.CharField(choices=[('age', 'Agricultural Engineering'), ('bch', 'Biochemistry'), ('che', 'Chemical Engineering'), ('chm', 'Chemistry'), ('cve', 'Civil Engineering'), ('csc', 'Computer Engineering'), ('eee', 'Elect. Elect. Engineering'), ('geo', 'Geology'), ('msc', 'Materials Science Engineering'), ('mth', 'Mathematics'), ('mee', 'Mechanical Engineering'), ('phy', 'Physics')], max_length=3, verbose_name='Department'),
        ),
    ]
