# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20170907_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.IntegerField(choices=[(1, 100), (2, 200), (3, 300), (4, 400), (5, 500), (6, 600)]),
        ),
    ]
